=== kevincouto/jsfront/doc/jsfront.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/application.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>
    <!DOCTYPE application SYSTEM "jsfront.dtd">
    <application>
    ...
    </application>
-->

<!ENTITY % Boolean "(true|false)">

<!-- Propriedades do jsf.core.Control -->
<!ENTITY % controlAttrs
 "name          CDATA          #IMPLIED
  enabled       %Boolean;      #IMPLIED"
  >

<!-- Propriedades do jsf.ui.DisplayObject -->
<!ENTITY % displayEvents
 "  onClick     CDATA   #IMPLIED
    onMouseDown CDATA   #IMPLIED
    onMouseUp   CDATA   #IMPLIED"
  >
<!ENTITY % displayAttrs
 "  %controlAttrs;
    %displayEvents;
    align               (left|top|right|bottom|client)          #IMPLIED
    dropEnabled         %Boolean;      #IMPLIED
    top                 CDATA          #IMPLIED
    left                CDATA          #IMPLIED
    width               CDATA          #IMPLIED
    height              CDATA          #IMPLIED
    right               CDATA          #IMPLIED
    bottom              CDATA          #IMPLIED
    visible             %Boolean;      #IMPLIED
    borderRadius        CDATA          #IMPLIED
    border              CDATA          #IMPLIED
    background          CDATA          #IMPLIED
    borderLeft          CDATA          #IMPLIED
    borderRight         CDATA          #IMPLIED
    borderTop           CDATA          #IMPLIED
    borderBottom        CDATA          #IMPLIED
    verticalCenter      CDATA          #IMPLIED
    horizontalCenter    CDATA          #IMPLIED
    style               CDATA          #IMPLIED
    margin              CDATA          #IMPLIED
    marginLeft          CDATA          #IMPLIED
    marginTop           CDATA          #IMPLIED
    marginBottom        CDATA          #IMPLIED
    marginRight         CDATA          #IMPLIED
    tipText             CDATA          #IMPLIED
    showEffect          CDATA          #IMPLIED
    hideEffect          CDATA          #IMPLIED"
  >

<!-- Propriedades do jsf.ui.JContainer -->
<!ENTITY % containerAttrs
 "  %displayAttrs;
    layout  (absolute|horizontal|vertical)          #IMPLIED
    caption  CDATA          #IMPLIED
    scroll  CDATA          #IMPLIED
    flex  CDATA          #IMPLIED
    grap  CDATA          #IMPLIED
    sprites  CDATA          #IMPLIED"
  >


<!-- Propriedades do jsf.ui.JModule -->
<!ENTITY % moduleAttrs "%containerAttrs;">

<!-- Tags que extendidas de jsf.ui.DisplayObject que podem ser adicionados em containers -->
<!ENTITY % allDisplayObjects
   "accordion | button | calendar | checkbox | combobox | container | datapicker | dataview |
     edit | grid | image | label | linkbutton | list | menubar | moduleloader | option | panel |
     password | radio | scrollbar | splitter | splitbutton | textbox | toolbar | treeview | sprites | tabpanel">

<!-- o elemento item, não contém elementos filhos e (TODO:pode conter qualquer atributo) -->
<!ELEMENT item EMPTY>
<!ATTLIST item label CDATA #IMPLIED >
  
<!-- array só permite um ou mais elementos item -->
<!ENTITY % array "(item)+">

<!-- permite zero ou um elemento array -->
<!ELEMENT dataProvider %array; >
    
<!--- reservad tag -->
<!ELEMENT import EMPTY>
<!ATTLIST import
    src CDATA #IMPLIED
  >

<!--- jsf.ui.JApplication -->
<!ELEMENT application (%allDisplayObjects; | import | package | template)*>
<!ATTLIST application
    %moduleAttrs;
    version CDATA   #IMPLIED
>

<!--- jsf.ui.JModule -->
<!ELEMENT module (%allDisplayObjects;)*>
<!ATTLIST module 
    %moduleAttrs;
>

<!--- jsf.ui.JContainer -->
<!ELEMENT container (%allDisplayObjects;)*>
<!ATTLIST container
    %containerAttrs;
  >

<!--- jsf.ui.JPanel -->
<!ELEMENT panel (%allDisplayObjects;)*>
<!ATTLIST panel
    %containerAttrs;
  >

<!--- jsf.ui.JTabPanel -->
<!ELEMENT tabpanel (container)*>
<!ATTLIST tabpanel
    %containerAttrs;
  >

<!--- jsf.ui.JToolbar -->
<!ELEMENT toolbar (%allDisplayObjects; | space | separator)*>
<!ATTLIST toolbar
    %displayAttrs;
  >
  
<!--- jsf.ui.JSprites -->
<!ELEMENT sprites EMPTY>
<!ATTLIST sprites
    %controlAttrs;
    width CDATA #IMPLIED
    height CDATA #IMPLIED
    image CDATA #IMPLIED
  >

<!--- jsf.ui.JSeparator -->
<!ELEMENT separator EMPTY>

<!--- jsf.ui.JSpace -->
<!ELEMENT space EMPTY>

<!--- jsf.ui.JButton -->
<!ELEMENT button EMPTY>
<!ATTLIST button
    %displayAttrs;
    caption CDATA #IMPLIED
  >

<!--- jsf.ui.JCalendar -->
<!ELEMENT calendar EMPTY>
<!ATTLIST calendar
    %displayAttrs;
  >

<!--- jsf.ui.JCheck -->
<!ELEMENT checkbox EMPTY>
<!ATTLIST checkbox
    %displayAttrs;
  >

<!--- jsf.ui.JCombo -->
<!ELEMENT combobox EMPTY>
<!ATTLIST combobox
    %displayAttrs;
  >

<!--- jsf.ui.JDataPicker -->
<!ELEMENT datapicker EMPTY>
<!ATTLIST datapicker
    %displayAttrs;
  >

<!--- jsf.ui.JDataView -->
<!ELEMENT dataview EMPTY>
<!ATTLIST dataview
    %displayAttrs;
  >

<!--- jsf.ui.JEdit -->
<!ELEMENT editbox EMPTY>
<!ATTLIST editbox
    %displayAttrs;
  >

<!--- jsf.ui.JGrid -->
<!ELEMENT datagrid EMPTY>
<!ATTLIST datagrid
    %displayAttrs;
  >

<!--- jsf.ui.JImage -->
<!ELEMENT image EMPTY>
<!ATTLIST image
    %displayAttrs;
  >

<!--- jsf.ui.JLabel -->
<!ELEMENT label EMPTY>
<!ATTLIST label
    %displayAttrs;
  >

<!--- jsf.ui.JLinkButton -->
<!ELEMENT linkbutton EMPTY>
<!ATTLIST linkbutton
    %displayAttrs;
  >

<!--- jsf.ui.JList -->
<!ELEMENT list (dataProvider | template)>
<!ATTLIST list
    %displayAttrs;
    template CDATA #IMPLIED
  >

<!--- jsf.ui.JMenu -->
<!ELEMENT menuitem EMPTY>
<!ELEMENT menu (menuitem)>
<!ATTLIST menu
    %displayAttrs;
  >

<!--- jsf.ui.JMenubar -->
<!ELEMENT menubar (menu)>
<!ATTLIST menubar
    %displayAttrs;
  >
<!--- jsf.ui.JModuleLoader -->
<!ELEMENT moduleloader EMPTY>
<!ATTLIST moduleloader
    %displayAttrs;
  >
<!--- jsf.ui.JOption -->
<!ELEMENT option EMPTY>
<!ATTLIST option
    %displayAttrs;
  >

<!--- jsf.ui.JPassword -->
<!ELEMENT password EMPTY>
<!ATTLIST password
    %displayAttrs;
  >

<!--- jsf.ui.JRadio -->
<!ELEMENT radio EMPTY>
<!ATTLIST radio
    %displayAttrs;
  >

<!--- jsf.ui.JScrollbar -->
<!ELEMENT scrollbar EMPTY>
<!ATTLIST scrollbar
    %displayAttrs;
  >

<!--- jsf.ui.JSplitButton -->
<!ELEMENT option EMPTY>
<!ATTLIST option
    %displayAttrs;
  >

<!--- jsf.ui.JSplitter -->
<!ELEMENT splitter EMPTY>
<!ATTLIST splitter
    %displayAttrs;
  >

<!--- jsf.ui.JText -->
<!ELEMENT textbox EMPTY>
<!ATTLIST textbox
    %displayAttrs;
  >

<!--- jsf.ui.JTree -->
<!ELEMENT treeview EMPTY>
<!ATTLIST treeview
    %displayAttrs;
  >

<!--- jsf.ui.JWindow -->
<!ELEMENT window EMPTY>
<!ATTLIST window
    %displayAttrs;
  >

=== kevincouto/jsfront/test/application.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE application SYSTEM "../doc/jsfront.dtd">
<application name="App" version="1.0" theme="google" onCreationComplete="onCreationComplete">
    <!-- <package name="custom" theme="false">libs/custom/</package> -->

    <import src="application.js" />
    
    <import src="jsf.core.Alert" />
    <import src="jsf.ui.JToolbar"     autoload="toolbar" />
    <import src="jsf.ui.JMenubar"     autoload="menubar" />
    <import src="jsf.ui.JSeparator"   autoload="separator" />
    <import src="jsf.ui.JButton"      autoload="button" />
    <import src="jsf.ui.JText"        autoload="textbox" />
    <import src="jsf.ui.JSplitButton" autoload="splitbutton" />
    <import src="jsf.ui.JMenu"        autoload="menu" />
    <import src="jsf.ui.JPanel"       autoload="panel" />
    <import src="jsf.ui.JSplitter"    autoload="splitter" />
    <import src="jsf.ui.JList"        autoload="list" />
    <import src="jsf.ui.JLabel"       autoload="label" />
    <import src="jsf.ui.JFormItem"    autoload="formitem" />
    
    <sprites name="icons" width="16" height="16" image="../themes/google/images/icons16.gif" />
    
    <!-- MENUS -->
    <menu name="menuArquivo" caption="Arquivo">
        <itens>
            <item label="Compartilhar" enabled="false" />
            <item label="-" />
            <item label="Novo" />
            <item label="Abrir" icon="[[2,3]]" />
            <item label="Renomear" />
            <item label="Fazer uma cópia" />
            <item label="Importar" />
            <item label="-" />
            <item label="Sair" />            
        </itens>
    </menu>
    <menu name="menuEditar" caption="Editar">
        <itens>
            <item label="Desfazer" />
            <item label="Refazer" />
            <item label="-" />
            <item label="Recortar" />
            <item label="Copiar" />
            <item label="Colar" />
            <item label="-" />
            <item label="Localizar e Substituir" />
            <item label="-" />
            <item label="Limpar" />
            <item label="Excluir Todos" />            
        </itens>
    </menu>
    
    <!-- INTERFACE -->
    <menubar itens='["menuArquivo","menuEditar"]' />
    <toolbar caption="Button" top="10" left="10">
        <button caption="Normal" width="100"/>
        <separator />
        <button caption="Disabled" enabled="false" />
        <separator />
        <button group="1" width="25" height="25" buttonStyle="flat" focuset="false"><caption><![CDATA[<b>N</b>]]></caption></button>
        <button group="1" width="25" height="25" buttonStyle="flat" focuset="false"><caption><![CDATA[<i>I</i>]]></caption></button>
        <button group="1" width="25" height="25" buttonStyle="flat" focuset="false"><caption><![CDATA[<u>U</u>]]></caption></button>
        <separator />
        <button caption="Togglet" togglet="true" iconMap="[[0,5]]" iconAlign="top" height="38" width="60" focuset="false" />
        <separator />
        <button iconMap="[[2,3]]" width="25" height="25" buttonStyle="flat" focuset="false" />
        <separator />
        <textbox />
        <separator />
        <splitbutton buttonStyle="flat" popup="menuArquivo" />
        <splitbutton />
    </toolbar>
    <container align="client" grap="4">
        <panel caption="Painel Esquerdo" align="left" grap="4">
            <list name="lstEsquerda" align="client" />
        </panel>
        <splitter margin="-4"/>
        <container align="client">
            <panel caption="Painel Direito" align="right">
                
            </panel>
            <splitter align="right"/>
            <panel caption="Painel Cliente" align="client">
                <container border="true" top="4" bottom="4" left="4" width="310">
                    <label top="3" left="4"><caption><![CDATA[<b style="font-size:14px">Form Elements</b>]]></caption></label>
                    <formitem top="30" caption="Nome:"><textbox /></formitem>
                    <formitem top="60" caption="Endereço:"><textbox /></formitem>
                    <formitem top="90" caption="Telefone Residencial:"><textbox /><textbox /></formitem>
                </container>
            </panel>
            <container height="120" align="bottom" border="true"></container>
            <splitter align="bottom"/>
        </container>
    </container>
    
</application>

=== kevincouto/jsfront/application.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE application SYSTEM "doc/jsfront.dtd">
<application grap="2" version="1.0">
    <!-- <package name="custom" theme="false">libs/custom/</package> -->

    <import src="application.js" />
    
    <import src="jsf.core.Alert" />
    <import src="jsf.ui.JToolbar" />
    <import src="jsf.ui.JButton" />
    <import src="jsf.ui.JPanel" />
    <import src="jsf.ui.JTree" />
    <import src="jsf.ui.JTabPanel" />
    <import src="jsf.ui.JList" />
    <import src="jsf.ui.JSplitter" />
    <import src="jsf.ui.JSeparator" />

    <sprites name="icons" width="16" height="16" image="images/icons_16x16.gif" />
    
    <!-- BEGIN INTERFACE -->
    <!-- top -->
    <toolbar>
        <button width="100" height="28" caption="New Project" onClick="actionNewProject"/>
        <button width="100" height="28" caption="Open Project"/>
        <separator />
        <button width="100" height="28" caption="New Module"/>
    </toolbar>
    
    <!-- left -->
    <container align="left" width="250">
        <panel align="top" height="200" caption="Module Tree">
            <treeview align="client" />
        </panel>
        <splitter align="top"/>
        <panel align="client" height="200" caption="Component Inspector">
            <tabpanel align="client">
                <container caption="Properties"></container>
                <container caption="Events"></container>
            </tabpanel>
        </panel>
    </container>
    <splitter />

    <!-- client -->
    <container name="tbpModules" align="client" style="{background:'#DDDDDD'}" border="true" scroll="true">
        <container name="ctnModule" width="800" height="600" top="10" left="10" border="true" background="#FFFFFF" />
    </container>

    <!-- right -->
    <container align="right" width="250">
        <panel caption="Components" align="client">
            <list name="lstUI" align="client" onMouseDown="lstUI_onMouseDown">
                <template><![CDATA[<b>#{label}</b>]]></template>
                <dataProvider>
                    <item label="label1"/>
                    <item label="label2"/>
                </dataProvider>
            </list>
        </panel>
    </container>
    <splitter align="right" />
    
</application>
